server:
  port: 8080

spring:
  profiles:
    active: mysql

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/batch
      username: sa

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ad?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
